name: Sustainability Linked Bonds Continuous Integration pipeline

on: [push]

jobs:
  build-and-test:
    name: Build & Test SLB dApp
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
        cache: 'pipenv'

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev
    - uses: pre-commit/action@v3.0.0
      name: "Linters and formatters check"
      with:
        extra_args: --all-files

    - name: Clone Algorand Sandbox
      run: cd .. && git clone https://github.com/algorand/sandbox.git

    - name: Run Algorand Sandbox
      shell: 'script -q -e -c "bash {0}"' # hacky hack to make TTY work
      run: cd ../sandbox && ./sandbox up dev -v

    - name: Sleep to allow the sandbox to start
      run: sleep 10

    - name: Run pytest
      run: pipenv run pytest --verbose

    - name: Stop running images
      run: cd ../sandbox && ./sandbox down
